### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 59notna**

### CODE REVIEW

**Comment by goranche** [comment]
@59notna Can you please explain this PR / commit.

First, the commit was made on Apr.25, which is a month and a half ago, and second, it only contains a single zip file.

Please add more context or the PR will be closed.

Thank you

**Comment by fabiofenoglio** [comment]
@goranche I am not the opener of this pull request but the code included in the zip appears to be the copy of the one from my repository:
https://github.com/fabiofenoglio/lelo-f1-python-sdk

@59notna can you please explain why you are redistributing my code, with no context and without proper attribution?

**Comment by goranche** [comment]
@fabiofenoglio weird...
I hadn't even opened the zip file (partly security / paranoia, but mainly because I don't work here anymore 🙈 just though it so weird, that I had to comment)

will close the PR if no reply by this evening 🤷‍♂️

**Comment by goranche** [comment]
@59notna I'm closing this Pull Request, as I find it suspicious.
If you think I'm wrong, please, add more context and an explanation, and reopen the PR

**Pull request closed without merging**
